name: Node.js CI

on: [pull_request]

jobs:
  check:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]
        node-version: [16.x]
        r-version: [4.1.x]
        python-version: [3.x]

    steps:
      # -----------------------
      # SETUP -----------------
      # -----------------------

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Ubuntu specific
      - name: Install curl
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install libcurl4-openssl-dev

      # Node
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node modules
        run: npm install

      # Typescript
      - name: Check types
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run check-types

      # R
      - name: Setup R v${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Cache Renv packages
        uses: r-lib/actions/setup-renv@v2

      - name: Renv snapshot
        run: Rscript -e "renv::snapshot()"

      # Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Build release
      - name: Build release
        run: npm run build-release

      - name: Link release
        run: npm link ./release

      # -----------------------
      # TEST ------------------
      # -----------------------

      - name: Run tests
        run: npm run test

      # -----------------------
      # WRAP UP ---------------
      # -----------------------

      - name: Upload artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.os }}-node${{ matrix.node-version }}-r${{ matrix.r-version }}-python${{ matrix.python-version }}-results
          path: check
